### ISSUE TITLE
Decide what to do with the first part of supplementary

### ISSUE THREAD

**Issue by maxbiostat** [fccoelho/paperLM1#10]
We show a couple things in that first part: 
(i) tail behaviour -- inverse beta approach is more conservative, and;
(ii)  how to include prior information on R(t) under the inverse beta sampling distribution.
These may be relevant to other people . [the other day we had a talk from a guy at Imperial working on Ebola where they employed R(t) calculations and complained about how to quantify uncertainty. Turns out we have a way to, uh?]

**Comment by fccoelho** [comment]
Great points,

When I sugest to give up on the supplement, I meant to drop only the
stochastic model. The R_t stuff we should incorporate back in the methods
section, the paper is still short. and would accommodate it well, I think.

I'll do that.

On Tue, Jan 27, 2015 at 6:14 PM, Luiz Max F. Carvalho <
notifications@github.com> wrote:

> Assigned #10 <https://github.com/fccoelho/paperLM1/issues/10> to @fccoelho
> <https://github.com/fccoelho>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fccoelho/paperLM1/issues/10#event-225622893>.
>



-- 
Flávio Codeço Coelho
================
+55(21) 3799-5551
Professor
Escola de Matemática Aplicada
Fundação Getulio Vargas
Praia de Botafogo, 190 sala 312
Rio de Janeiro - RJ
22250-900
Brasil

**Comment by maxbiostat** [comment]
Solved, so closing.
