### ISSUE TITLE
Remove text S1

### ISSUE THREAD

**Issue by maxbiostat** [fccoelho/paperLM1#12]
Since it would be nice to have a clean repo. Just save the bit on the stoch model elsewhere for further use and -- since the other bits are now on the main text -- delete the file.

**Comment by maxbiostat** [comment]
Also, may want to move the stochastic_model/ directory to a safe location and get rid of it in the repo.

**Comment by fccoelho** [comment]
Sure, will do that.

**Comment by maxbiostat** [comment]
I do, but the intention is not to hide anything. Rather is not to confuse the reader that comes to the repository and sees a folder called stochastic_model when we present none in the manuscript.
Building on that, we may want to re-name the repo and give it a more informative README. I can do that.
Just say the word = create an issue an assign it to me.
