### ISSUE TITLE
Comment 1: simulation

### ISSUE THREAD

**Issue by maxbiostat** [fccoelho/paperLM1#21]
The authors have developed a novel statistical method for analyzing a complex disease system. The theoretical foundation of the method appears sound, and the explanation of why this method is particularly important for a multi-pathogen system such as dengue is well articulated. However, the authors provide very little information about the performance of the method in practice. As one example, they make the claim: "The method to quantify uncertainty proposed here provides more conservative credibility intervals, and therefore offers protection against false alarms." However they provide little empirical evidence to back up this claim. Since several simplifying assumptions are made within the likelihood (e.g. fixing sigma^2, tau, R_t), this might lead to underestimates of the uncertainty. I would suggest a small simulation study to illustrate that this method works and can estimate accurately the parameters indicated.

**Comment by fccoelho** [comment]
This simulation is the same as the one done over and over in the inference loop.  We must only fix the parameters and replace data with a simulated run for the inference. The inference should return the parameters used to generated the simulated dataset with maximum posterior probability.

**Comment by maxbiostat** [comment]
Agreed.

On 7 June 2015 at 19:21, Flávio Codeço Coelho <notifications@github.com>
wrote:

> This simulation is the same as the one done over and over in the inference
> loop. We must only fix the parameters and replace data with a simulated run
> for the inference. The inference should return the parameters used to
> generated the simulated dataset with maximum posterior probability.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fccoelho/paperLM1/issues/21#issuecomment-109785274>.
>



-- 
Luiz Max Fagundes de Carvalho
PhD student, Institute of Evolutionary Biology,  School of Biological
Sciences,
Ashworth Laboratories, Ash 2, office 123
University of Edinburgh, United Kingdom.
http://br.linkedin.com/pub/luiz-max-carvalho/49/687/283

**Comment by fccoelho** [comment]
I am running the inference here, on simulated data,  and as expected, the fit is perfect and I recover the parameters of the simulation without any problem. I will commit the code as soon as I finish the tests. Ideas on how to include this in the supplementary material are welcome. I think we don't need to simulate with the parameters of all years, what do you think @maxbiostat? it will generate a lot of figures.

**Comment by maxbiostat** [comment]
There is a small problem, however: the claim about the "conservativeness" of the credibility intervals is about Rt. Thus, we also need an example that shows this. I have a very simple one in mind. 
What are we using for the time-varying FoI in the simulated data? A senoid?

**Comment by fccoelho** [comment]
I am using the Rt estimated from data.

On Tue, Jun 9, 2015 at 7:11 AM, Luiz Max F. Carvalho <
notifications@github.com> wrote:

> There is a small problem, however: the claim about the "conservativeness"
> of the credibility intervals is about Rt. Thus, we also need an example
> that shows this. I have a very simple one in mind.
> What are we using for the time-varying FoI in the simulated data? A senoid?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fccoelho/paperLM1/issues/21#issuecomment-110300967>.
>



-- 
Flávio Codeço Coelho
================
+55(21) 3799-5551
Professor
Escola de Matemática Aplicada
Fundação Getulio Vargas
Praia de Botafogo, 190 sala 312
Rio de Janeiro - RJ
22250-900
Brasil

**Comment by maxbiostat** [comment]
OK.
